<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise</title>
</head>
<body>
    <script>
//resolve reject all ract
//resolve== then reject ==catch
        // let promise = new Promise((resolve, reject) => {
        //     resolve(1111);
        // })

        // promise.then( response => {
        //     console.log('成功');
        //     console.log(response);
        // }).catch( error => {
        //     console.log('失败');
        // })
        //链式
        function promise1(status){
            return new Promise((resolve, reject) => {
                if(status){
                    console.log('第一个promise')
                    resolve('第一个promise成功')
                }
                if(!status){
                    console.log('第二个promise');
                    reject('地个pro，ise 返回数据失败');      
                }

            })
        }
        function promise2(status){
            return new Promise((resolve, reject) => {
                if(status){
                    console.log('第2个promise')
                    resolve('第2个promise成功')
                }
                if(!status){
                    console.log('第2个promise');
                    reject('地个2pro，ise 返回数据失败');      
                }

            })
        }
        // promise1(true).then( (response) => {
        //     console.log(response);
        //     return promise2(true);
        // }).then( (response) => {
        //     console.log(response);
        //     // promise2(true);
        // }).catch( error => {
        //     console.log(error)
        // })
        //all方法 数组内promise必须全部成功（全部返回resolve，才会then ，只要有一个不成功（返回reject）就会catch
        // Promise.all([promise1(true),promise2(true)]).then(response => {
        //     console.log('全部调用成功')
        // }).catch( error => {
        //     console.log('有些调用失败')
        // });
        //race 数组 当执行的时候遇到的返回结果是resolve的时候，那么就会继续向下链式执行
        //finanl理解 ： rece知哟啊有一个返回resolve成功就会回调 then ，但是如果第一个返回reject那么就失败了
        Promise.race([promise1(true),promise2(true)]).then(response => {
            console.log('全部调用成功')
        }).catch( error => {
            console.log('有些调用失败')
        });    
    </script>
</body>
</html>